var VIDEO_LIBRARY = [
  {
    "title": "InBrief: The Science of Early Childhood Development",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=WO-CB2nsqTA",
    "videoId": "WO-CB2nsqTA",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "3:58",
    "lang": "en",
    "category": "education",
    "desc": "Comprehensive overview of early childhood development science from Harvard, covering brain development, serve-and-return interactions, and the importance of early experiences.",
    "descFa": ""
  },
  {
    "title": "Experiences Build Brain Architecture",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=VNNsN9IJkws",
    "videoId": "VNNsN9IJkws",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "1:57",
    "lang": "en",
    "category": "education",
    "desc": "How experiences in early childhood literally build the architecture of the developing brain, from Harvard's Center on the Developing Child.",
    "descFa": ""
  },
  {
    "title": "5 Steps for Brain-Building Serve and Return",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=KNrnZag17Ek",
    "videoId": "KNrnZag17Ek",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "6:07",
    "lang": "en",
    "category": "education",
    "desc": "A step-by-step guide to brain-building serve and return interactions between caregivers and children, from Harvard.",
    "descFa": ""
  },
  {
    "title": "Serve & Return Interaction Shapes Brain Circuitry",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=m_5u8-QSh6A",
    "videoId": "m_5u8-QSh6A",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "1:43",
    "lang": "en",
    "category": "education",
    "desc": "How serve and return interactions between children and caregivers shape brain circuitry during early development.",
    "descFa": ""
  },
  {
    "title": "How Early Childhood Experiences Affect Lifelong Health and Learning",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=IipVaPKnjRk",
    "videoId": "IipVaPKnjRk",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "5:11",
    "lang": "en",
    "category": "education",
    "desc": "How early childhood experiences affect lifelong health and learning, based on research from Harvard.",
    "descFa": ""
  },
  {
    "title": "Toxic Stress Derails Healthy Development",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=rVwFkcOZHJw",
    "videoId": "rVwFkcOZHJw",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "1:52",
    "lang": "en",
    "category": "education",
    "desc": "How toxic stress can derail healthy development in children and what can be done about it.",
    "descFa": ""
  },
  {
    "title": "How Children and Adults Can Build Core Capabilities for Life",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=6NehuwDA45Q",
    "videoId": "6NehuwDA45Q",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "5:34",
    "lang": "en",
    "category": "education",
    "desc": "How children and adults can build core capabilities for lifelong learning and resilience.",
    "descFa": ""
  },
  {
    "title": "InBrief: Early Childhood Program Effectiveness",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=_BgtFYEC1Yk",
    "videoId": "_BgtFYEC1Yk",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "4:57",
    "lang": "en",
    "category": "education",
    "desc": "What makes early childhood programs effective, based on research from Harvard's Center on the Developing Child.",
    "descFa": ""
  },
  {
    "title": "InBrief: Executive Function: Skills for Life and Learning",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=efCq_vHUMqs",
    "videoId": "efCq_vHUMqs",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "5:36",
    "lang": "en",
    "category": "education",
    "desc": "Executive function skills explained — the mental processes that enable children to plan, focus, remember, and juggle multiple tasks.",
    "descFa": ""
  },
  {
    "title": "InBrief: The Science of Resilience",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=1r8hj72bfGo",
    "videoId": "1r8hj72bfGo",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "2:30",
    "lang": "en",
    "category": "education",
    "desc": "The science of resilience — how children can overcome adversity with the right support.",
    "descFa": ""
  },
  {
    "title": "InBrief: The Science of Neglect",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=bF3j5UVCSCA",
    "videoId": "bF3j5UVCSCA",
    "channel": "Center on the Developing Child at Harvard University",
    "duration": "5:58",
    "lang": "en",
    "category": "education",
    "desc": "The science of neglect — how the absence of interaction affects child development.",
    "descFa": ""
  },
  {
    "title": "How Every Child Can Thrive by Five | Molly Wright | TED",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=aISXCw0Pi94",
    "videoId": "aISXCw0Pi94",
    "channel": "TED",
    "duration": "7:43",
    "lang": "en",
    "category": "education",
    "desc": "Molly Wright shows how every child can thrive by five through simple, evidence-based interactions with caregivers.",
    "descFa": ""
  },
  {
    "title": "The Single Most Important Parenting Strategy | Becky Kennedy | TED",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=PHpPtdk9rco",
    "videoId": "PHpPtdk9rco",
    "channel": "TED",
    "duration": "14:04",
    "lang": "en",
    "category": "education",
    "desc": "Becky Kennedy presents the single most important parenting strategy — how repair strengthens relationships with children.",
    "descFa": ""
  },
  {
    "title": "How play helps a kid’s brain grow - Jesse Ilhardt",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=12O3pZpTvGs",
    "videoId": "12O3pZpTvGs",
    "channel": "TED-Ed Educator Talks",
    "duration": "5:14",
    "lang": "en",
    "category": "education",
    "desc": "How play helps a kid's brain grow — Jesse Ilhardt explains the neuroscience behind children's play.",
    "descFa": ""
  },
  {
    "title": "What’s the smartest age? - Shannon Odell",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=sbCvQbBi2G8",
    "videoId": "sbCvQbBi2G8",
    "channel": "TED-Ed",
    "duration": "4:53",
    "lang": "en",
    "category": "education",
    "desc": "What's the smartest age? Shannon Odell explores cognitive development across different childhood stages.",
    "descFa": ""
  },
  {
    "title": "Why kids need to take more risks",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=kRAl4Xgs_NU",
    "videoId": "kRAl4Xgs_NU",
    "channel": "TED-Ed",
    "duration": "5:24",
    "lang": "en",
    "category": "education",
    "desc": "Why kids need to take more risks — the importance of risk-taking in childhood development.",
    "descFa": ""
  },
  {
    "title": "What is the most important influence on child development | Tom Weisner | TEDxUCLA",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=gIZ8PkLMMUo",
    "videoId": "gIZ8PkLMMUo",
    "channel": "TEDx Talks",
    "duration": "8:42",
    "lang": "en",
    "category": "education",
    "desc": "What is the most important influence on child development — Tom Weisner examines environmental and familial factors.",
    "descFa": ""
  },
  {
    "title": "How to Raise Kids Who Can Handle Hard Things | Kathryn Hecht | TED",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=lRXkSn4pUyU",
    "videoId": "lRXkSn4pUyU",
    "channel": "TED",
    "duration": "16:45",
    "lang": "en",
    "category": "education",
    "desc": "How to raise kids who can handle hard things — building resilience and emotional toughness in children.",
    "descFa": ""
  },
  {
    "title": "Yuko Munakata: The science behind how parents affect child development | TED",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=evw0h1kg-j4",
    "videoId": "evw0h1kg-j4",
    "channel": "TED",
    "duration": "17:12",
    "lang": "en",
    "category": "education",
    "desc": "The science behind how parents affect child development — Yuko Munakata presents research on parenting.",
    "descFa": ""
  },
  {
    "title": "Webinar: Culturally Appropriate Positive Guidance for Young Children in Our Care",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=JndJpUtSgQQ",
    "videoId": "JndJpUtSgQQ",
    "channel": "NAEYC",
    "duration": "59:11",
    "lang": "en",
    "category": "education",
    "desc": "NAEYC webinar on culturally appropriate positive guidance strategies for young children in diverse classrooms.",
    "descFa": ""
  },
  {
    "title": "Learn about the National Association for the Education of Young Children (NAEYC)",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=MxZz2OqRVeo",
    "videoId": "MxZz2OqRVeo",
    "channel": "NAEYC",
    "duration": "2:23",
    "lang": "en",
    "category": "education",
    "desc": "An introduction to the National Association for the Education of Young Children (NAEYC) and its mission.",
    "descFa": ""
  },
  {
    "title": "Introduction to NAEYC Accreditation Standards",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=rgJf1LikBJ0",
    "videoId": "rgJf1LikBJ0",
    "channel": "NAEYC",
    "duration": "12:02",
    "lang": "en",
    "category": "education",
    "desc": "Overview of NAEYC accreditation standards for high-quality early childhood education programs.",
    "descFa": ""
  },
  {
    "title": "Early Childhood Education Teaching Strategies",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=9152_f1FyAQ",
    "videoId": "9152_f1FyAQ",
    "channel": "Teachings in Education",
    "duration": "3:24",
    "lang": "en",
    "category": "education",
    "desc": "Comprehensive overview of effective teaching strategies for early childhood education settings.",
    "descFa": ""
  },
  {
    "title": "6 Practical Tips for New Preschool Teachers",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=wO-veIY05fQ",
    "videoId": "wO-veIY05fQ",
    "channel": "Edutopia",
    "duration": "2:51",
    "lang": "en",
    "category": "education",
    "desc": "Six practical tips for new preschool teachers from Edutopia — classroom setup, routines, and engagement.",
    "descFa": ""
  },
  {
    "title": "Early Childhood Education: The Power of Interactions",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=ePkuGdX_np8",
    "videoId": "ePkuGdX_np8",
    "channel": "ESC Region 13",
    "duration": "3:44",
    "lang": "en",
    "category": "education",
    "desc": "How meaningful interactions between teachers and young children create powerful learning moments.",
    "descFa": ""
  },
  {
    "title": "How to Discipline Toddlers | Child Mind Institute",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=mAKEEG6KrAE",
    "videoId": "mAKEEG6KrAE",
    "channel": "Child Mind Institute",
    "duration": "2:45",
    "lang": "en",
    "category": "education",
    "desc": "Child Mind Institute shares evidence-based strategies for disciplining toddlers with empathy and effectiveness.",
    "descFa": ""
  },
  {
    "title": "Improving early child development with words: Dr. Brenda Fitzgerald at TEDxAtlanta",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=y8qc8Aa3weE",
    "videoId": "y8qc8Aa3weE",
    "channel": "TEDx Talks",
    "duration": "21:57",
    "lang": "en",
    "category": "education",
    "desc": "Dr. Brenda Fitzgerald discusses improving early childhood development through words and language at TEDx.",
    "descFa": ""
  },
  {
    "title": "The fascinating reason you loved peek-a-boo",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=qKM4JzToM-A",
    "videoId": "qKM4JzToM-A",
    "channel": "TED-Ed",
    "duration": "5:29",
    "lang": "en",
    "category": "education",
    "desc": "The fascinating science behind why babies love peek-a-boo and what it teaches about cognitive development.",
    "descFa": ""
  },
  {
    "title": "Developmental Milestones Made Easy (With Memory Tool!)",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=eNHA9VNbuhk",
    "videoId": "eNHA9VNbuhk",
    "channel": "Rhesus Medicine",
    "duration": "10:50",
    "lang": "en",
    "category": "education",
    "desc": "Developmental milestones made easy with a memory tool — helpful guide for parents and educators.",
    "descFa": ""
  },
  {
    "title": "How does your baby compare? (What every parent needs to hear about milestones)",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=ytyXAZJ0V4Q",
    "videoId": "ytyXAZJ0V4Q",
    "channel": "Emma Hubbard",
    "duration": "5:30",
    "lang": "en",
    "category": "education",
    "desc": "Emma Hubbard explains how to compare your baby's milestones to what's typical at each age.",
    "descFa": ""
  },
  {
    "title": "ASHA’s Developmental Milestones: Communication (Hearing, Speech, and Language)",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=1JpCAB-4iCw",
    "videoId": "1JpCAB-4iCw",
    "channel": "American Speech-Language-Hearing Association",
    "duration": "4:25",
    "lang": "en",
    "category": "education",
    "desc": "ASHA's guide to developmental milestones in communication — hearing, speech, and language.",
    "descFa": ""
  },
  {
    "title": "10 Tips for Parenting Anxious Kids | Child Mind Institute",
    "titleFa": "",
    "url": "https://www.youtube.com/watch?v=c5ASysmOH_I",
    "videoId": "c5ASysmOH_I",
    "channel": "Child Mind Institute",
    "duration": "6:08",
    "lang": "en",
    "category": "education",
    "desc": "10 practical tips for parenting anxious kids from the Child Mind Institute.",
    "descFa": ""
  },
  {
    "title": "",
    "titleFa": "تربیت کودک از تولد تا ۳ سالگی | دکتر فرهنگ هلاکویی | قسمت ۱",
    "url": "https://www.youtube.com/watch?v=dKDXtfllInU",
    "videoId": "dKDXtfllInU",
    "channel": "Dr. Holakouee Official Channel",
    "duration": "2:11:05",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "سمینار جامع دکتر فرهنگ هلاکویی درباره اصول تربیت کودک از بدو تولد تا سه سالگی. بررسی نیازهای عاطفی و روانی کودک در مراحل اولیه رشد."
  },
  {
    "title": "",
    "titleFa": "۱۳ اشتباه بزرگ در تربیت فرزند | دکتر هلاکویی",
    "url": "https://www.youtube.com/watch?v=1PyrD6_6Gio",
    "videoId": "1PyrD6_6Gio",
    "channel": "Dr. Holakouee Official Channel",
    "duration": "2:27",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "مرور سریع ۱۳ اشتباه رایج والدین در تربیت فرزندان از دیدگاه دکتر هلاکویی. نکات کلیدی برای پرهیز از رفتارهای مخرب والدینی."
  },
  {
    "title": "",
    "titleFa": "تعلیم و تربیت کودک چهار ساله",
    "url": "https://www.youtube.com/watch?v=AoJYlP3SQcs",
    "videoId": "AoJYlP3SQcs",
    "channel": "Dr. Holakouee Official Channel",
    "duration": "35:45",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "بررسی ویژگی‌های رشدی و تربیتی کودکان چهار ساله. راهکارهای عملی برای والدین جهت پرورش صحیح کودک در این سن حساس."
  },
  {
    "title": "",
    "titleFa": "سمینار اصول پدری و مادری دکتر فرهنگ هلاکویی - قسمت اول",
    "url": "https://www.youtube.com/watch?v=qa_xDilkmF8",
    "videoId": "qa_xDilkmF8",
    "channel": "Dr. Holakouee Official Channel",
    "duration": "1:39:49",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "سمینار جامع اصول پدری و مادری توسط دکتر فرهنگ هلاکویی. بررسی نقش والدین در شکل‌گیری شخصیت کودک و ایجاد محیط خانوادگی سالم."
  },
  {
    "title": "",
    "titleFa": "برخورد صحیح والدین با کودکان زودرنج و حساس",
    "url": "https://www.youtube.com/watch?v=74X-SLz-hso",
    "videoId": "74X-SLz-hso",
    "channel": "روانشناسی کودک و نوجوان",
    "duration": "11:30",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آموزش روش‌های برخورد صحیح با کودکانی که دارای شخصیت حساس و زودرنج هستند. تکنیک‌های روانشناسی برای مدیریت احساسات کودک."
  },
  {
    "title": "",
    "titleFa": "با کودکان لجباز چطور برخورد کنیم؟",
    "url": "https://www.youtube.com/watch?v=WwkA9LcTgCc",
    "videoId": "WwkA9LcTgCc",
    "channel": "Dr Banihashemian",
    "duration": "17:45",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "راهنمای کاربردی برخورد با کودکان لجباز. ارائه راهکارهای مؤثر برای مدیریت رفتارهای مقاومتی کودکان بدون تنش و تعارض."
  },
  {
    "title": "",
    "titleFa": "بهترین روش تربیت فرزند | بایدها و نبایدهای رفتار با کودک",
    "url": "https://www.youtube.com/watch?v=V7EcokDQNpk",
    "videoId": "V7EcokDQNpk",
    "channel": "Shahram Eslami",
    "duration": "39:31",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "بررسی جامع بایدها و نبایدهای تربیت فرزند. ارائه اصول علمی و کاربردی برای والدین جهت تربیت صحیح فرزندان."
  },
  {
    "title": "",
    "titleFa": "پنج اشتباه تربیتی مادران که آینده فرزند رو نابود می‌کنه | از زبان کارل یونگ",
    "url": "https://www.youtube.com/watch?v=tWid1KZZzbI",
    "videoId": "tWid1KZZzbI",
    "channel": "comma podcast",
    "duration": "9:01",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "بررسی پنج اشتباه رایج مادران در تربیت فرزند از منظر روانشناسی تحلیلی کارل یونگ. تأثیر این اشتباهات بر شخصیت آینده کودک."
  },
  {
    "title": "",
    "titleFa": "از صفر تا صد قوانین تربیت سالم کودک (داکتر محمود انوشه)",
    "url": "https://www.youtube.com/watch?v=rO4V2-1z69Y",
    "videoId": "rO4V2-1z69Y",
    "channel": "Rangila Belqis",
    "duration": "47:15",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آموزش جامع قوانین تربیت سالم کودک توسط داکتر محمود انوشه. از اصول اولیه تا تکنیک‌های پیشرفته تربیت فرزند."
  },
  {
    "title": "",
    "titleFa": "مراحل رشد کودک",
    "url": "https://www.youtube.com/watch?v=jDcwHADWOEE",
    "videoId": "jDcwHADWOEE",
    "channel": "عاطفه صادقیان",
    "duration": "9:06",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "بررسی کامل مراحل مختلف رشد کودک از نظر جسمی، ذهنی و عاطفی. شناخت مراحل رشد برای والدین و مربیان ضروری است."
  },
  {
    "title": "",
    "titleFa": "رشد ذهنی کودک ماه به ماه | از تولد تا ۲ سالگی",
    "url": "https://www.youtube.com/watch?v=wTuH69RB3y8",
    "videoId": "wTuH69RB3y8",
    "channel": "Zarafeyejadooyi",
    "duration": "4:15",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "توضیح رشد مغز و ذهن کودک ماه به ماه از تولد تا دو سالگی. درک مراحل رشد عصبی به والدین کمک می‌کند تا محیط مناسب فراهم کنند."
  },
  {
    "title": "",
    "titleFa": "رشد حسی حرکتی کودکان | قسمت اول",
    "url": "https://www.youtube.com/watch?v=ARWZyYSn88Q",
    "videoId": "ARWZyYSn88Q",
    "channel": "بازی‌های حرکتی خلاق",
    "duration": "16:16",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آموزش مراحل رشد حسی-حرکتی کودکان و تأثیر بازی‌های حرکتی بر پرورش مهارت‌های جسمی و شناختی کودک."
  },
  {
    "title": "",
    "titleFa": "آموزش والدین | تأثیر والدین روی فرزندان",
    "url": "https://www.youtube.com/watch?v=y1Kvmh9CmiE",
    "videoId": "y1Kvmh9CmiE",
    "channel": "Dr.Pooran Khorooshi",
    "duration": "2:52",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "بررسی تأثیر مستقیم رفتار و شخصیت والدین بر شکل‌گیری شخصیت فرزندان. نکات کلیدی برای والدین آگاه."
  },
  {
    "title": "",
    "titleFa": "مهارتهای زندگی برای کودکان؛ تربیت کودک، آموزش والدین، مشکلات رفتاری کودکان",
    "url": "https://www.youtube.com/watch?v=RjD9gKAQvqs",
    "videoId": "RjD9gKAQvqs",
    "channel": "Dr Leila Rasti",
    "duration": "11:58",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آموزش مهارت‌های زندگی ضروری برای کودکان و راهکارهای والدینی برای حل مشکلات رفتاری رایج در دوران کودکی."
  },
  {
    "title": "",
    "titleFa": "تقویت مهارت‌های اجتماعی کودکان: راهنمایی برای والدین",
    "url": "https://www.youtube.com/watch?v=YtmJikTfd7g",
    "videoId": "YtmJikTfd7g",
    "channel": "1percenters",
    "duration": "5:51",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "راهنمای تقویت مهارت‌های اجتماعی کودکان شامل برقراری ارتباط، همکاری و مدیریت احساسات. تمرین‌های کاربردی برای والدین."
  },
  {
    "title": "",
    "titleFa": "آموزش جملات اولیه به کودکان | آموزش زبان فارسی",
    "url": "https://www.youtube.com/watch?v=qIC-IhyTsbA",
    "videoId": "qIC-IhyTsbA",
    "channel": "mahdeshid",
    "duration": "30:42",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آموزش جملات و کلمات اولیه فارسی به کودکان خردسال. روش‌های خلاقانه آموزش زبان مادری به کودکان پیش‌دبستانی."
  },
  {
    "title": "",
    "titleFa": "آموزش پیش دبستانی مفاهیم ریاضی: مقدمه",
    "url": "https://www.youtube.com/watch?v=clq3FNZQejE",
    "videoId": "clq3FNZQejE",
    "channel": "بتول فتح‌الله",
    "duration": "10:42",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آموزش مفاهیم پایه ریاضی برای کودکان پیش‌دبستانی شامل شمارش، اشکال هندسی و مفاهیم اولیه عدد."
  },
  {
    "title": "",
    "titleFa": "خلاقیت در آموزش: طراحی فعالیت‌های جذاب و آموزشی برای کودکان",
    "url": "https://www.youtube.com/watch?v=_B0xC-ab4oc",
    "videoId": "_B0xC-ab4oc",
    "channel": "yad begirim",
    "duration": "4:26",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "ایده‌های خلاقانه برای طراحی فعالیت‌های آموزشی جذاب برای کودکان. مناسب مربیان پیش‌دبستانی و والدین علاقه‌مند."
  },
  {
    "title": "",
    "titleFa": "معرفی روش مونته‌سوری در تربیت و پرورش کودکان",
    "url": "https://www.youtube.com/watch?v=T5jGS6EBv3o",
    "videoId": "T5jGS6EBv3o",
    "channel": "خانه شاد",
    "duration": "10:36",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "آشنایی با روش مونته‌سوری در تربیت کودکان، تاریخچه و مزایای این روش آموزشی محبوب در پیش‌دبستانی‌ها."
  },
  {
    "title": "",
    "titleFa": "از تولد تا سه سالگی: نکات مهم در مورد بازی و اسباب بازی کودکان",
    "url": "https://www.youtube.com/watch?v=vpx2g7OWrbo",
    "videoId": "vpx2g7OWrbo",
    "channel": "Dr. Holakouee Official Channel",
    "duration": "14:41",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "بررسی نقش بازی و اسباب‌بازی مناسب در رشد کودک از تولد تا سه سالگی. انتخاب اسباب‌بازی بر اساس سن و مراحل رشد."
  },
  {
    "title": "",
    "titleFa": "چرا فرزندانمان حرف شنوی ندارند؟",
    "url": "https://www.youtube.com/watch?v=FazA7lgojFo",
    "videoId": "FazA7lgojFo",
    "channel": "همراز",
    "duration": "13:30",
    "lang": "fa",
    "category": "parenting",
    "desc": "",
    "descFa": "تحلیل دلایل عدم گوش‌دهی کودکان به والدین و ارائه راهکارهای مؤثر برای بهبود ارتباط و ایجاد انگیزه در فرزندان."
  },
  {
    "title": "Maternal & Early Childhood Nutrition",
    "titleFa": "تغذیه مادر و کودک",
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Maternal%2C_Infant_and_Early_Childhood_Nutrition_%E2%80%94_The_Thousand_Day_Window_of_Opportunity.webm",
    "videoId": "",
    "channel": "CDC",
    "duration": "",
    "lang": "en",
    "category": "health",
    "desc": "First 1000 days nutrition for brain development",
    "descFa": "هزه روز اول تغذیه برای رشد مغز"
  },
  {
    "title": "Babies on the Move — Vaccination",
    "titleFa": "واکسیناسیون نوزادان",
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/57/Babies_on_the_Move-_Protecting_Babies_with_Vaccination.webm",
    "videoId": "",
    "channel": "CDC",
    "duration": "",
    "lang": "en",
    "category": "health",
    "desc": "Protecting babies from 14 diseases through vaccination",
    "descFa": "محافظت نوزادان از ۱۴ بیماری با واکسیناسیون"
  },
  {
    "title": "Welcome to Parenthood",
    "titleFa": "خوش آمدید به پدر و مادر شدن",
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Welcome_to_Parenthood.webm",
    "videoId": "",
    "channel": "CDC",
    "duration": "",
    "lang": "en",
    "category": "parenting",
    "desc": "Guide for new parents about baby care milestones",
    "descFa": "راهنمای والدین جدید درباره مراقبت از نوزاد"
  }
];
